# Generated by Django 5.1.4 on 2025-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_customuser_created_at_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
