# Generated by Django 5.1.4 on 2025-04-16 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sample title', max_length=200)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='offers/')),
                ('description', models.TextField(default='sample description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('min_delivery_time', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='sample description')),
                ('title', models.CharField(default='sample title', max_length=200)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('delivery_time', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('offer_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
            ],
        ),
    ]
