# Generated by Django 5.1.4 on 2025-05-21 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0, help_text='-1 for unlimited', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
