# Generated by Django 5.1.4 on 2025-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
