# Generated by Django 5.1.4 on 2025-04-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_min_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='delivery_time',
            new_name='delivery_time_in_days',
        ),
    ]
